# Generated by Django 2.1.2 on 2019-02-17 12:38

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(2, 'Recipient'), (5, 'LocalBody'), (6, 'Admin')], default=6)),
                ('name', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BloodDonationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('organizer', models.CharField(default='', max_length=50)),
                ('contact', models.CharField(default='', max_length=10)),
                ('category', models.CharField(choices=[('edu', 'Education'), ('busi', 'Business'), ('pension', 'Pension'), ('loans', 'Loans'), ('agri', 'Agriculture'), ('health', 'Healthcare'), ('others', 'Others')], default='Others', max_length=12)),
                ('description', models.CharField(default='', max_length=500)),
                ('el_age', models.CharField(default='', max_length=2)),
                ('el_education', models.CharField(choices=[('u', 'Uneducated'), ('sch', 'School'), ('ssc', 'SSC'), ('hsc', 'HSC'), ('grad', 'Graduate'), ('postgrad', 'Post Graduate')], default='Uneducated', max_length=13)),
                ('el_designation', models.CharField(choices=[('Student', 'Student'), ('Govt. Employee', 'Govt. Employee'), ('Businessman', 'Business'), ('Private Employee', 'Private_Employee'), ('Unemployed', 'Unemployed'), ('Others', 'Others')], default='Others', max_length=16)),
                ('el_income', models.IntegerField(default=0)),
                ('el_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('NA', 'N/A')], default='N/A', max_length=1)),
                ('link', models.TextField(default='', validators=[django.core.validators.URLValidator()])),
                ('poster', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LocalBodies',
            fields=[
                ('name', models.CharField(default='', max_length=40)),
                ('location', models.CharField(default='', max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(default='', max_length=40)),
                ('last_name', models.CharField(default='', max_length=40)),
                ('age', models.CharField(default='', max_length=2)),
                ('education', models.CharField(choices=[('u', 'Uneducated'), ('sch', 'School'), ('ssc', 'SSC'), ('hsc', 'HSC'), ('grad', 'Graduate'), ('postgrad', 'Post Graduate')], default='Uneducated', max_length=13)),
                ('designation', models.CharField(choices=[('Student', 'Student'), ('Govt_Employee', 'Govt. Employee'), ('Business', 'Businessman'), ('Private_Employee', 'Private Employee'), ('Unemployed', 'Unemployed'), ('Others', 'Others')], default='Others', max_length=16)),
                ('income', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Other', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='blooddonationevent',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
