# Generated by Django 2.1.2 on 2019-02-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonationevent',
            name='el_designation',
            field=models.CharField(choices=[('Student', 'Student'), ('Govt. Employee', 'Govt. Employee'), ('Businessman', 'Business'), ('Private Employee', 'Private_Employee'), ('Unemployed', 'Unemployed'), ('Others', 'Others')], default='Others', max_length=16),
        ),
        migrations.AlterField(
            model_name='blooddonationevent',
            name='el_education',
            field=models.CharField(choices=[('u', 'Uneducated'), ('sch', 'School'), ('ssc', 'SSC'), ('hsc', 'HSC'), ('grad', 'Graduate'), ('postgrad', 'Post Graduate')], default='Uneducated', max_length=13),
        ),
        migrations.AlterField(
            model_name='blooddonationevent',
            name='el_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('NA', 'N/A')], default='N/A', max_length=1),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='designation',
            field=models.CharField(choices=[('Student', 'Student'), ('Govt_Employee', 'Govt. Employee'), ('Business', 'Businessman'), ('Private_Employee', 'Private Employee'), ('Unemployed', 'Unemployed'), ('Others', 'Others')], default='Others', max_length=16),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='education',
            field=models.CharField(choices=[('u', 'Uneducated'), ('sch', 'School'), ('ssc', 'SSC'), ('hsc', 'HSC'), ('grad', 'Graduate'), ('postgrad', 'Post Graduate')], default='Uneducated', max_length=13),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Other', max_length=1),
        ),
    ]
