# Generated by Django 2.1.2 on 2019-02-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20190216_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonationevent',
            name='category',
            field=models.CharField(choices=[('edu', 'Education'), ('busi', 'Business'), ('pension', 'Pension'), ('loans', 'Loans'), ('agri', 'Agriculture'), ('health', 'Healthcare'), ('others', 'Others')], default='Others', max_length=12),
        ),
    ]
